### ISSUE TITLE
Cannot connect to Tuya devices

### ISSUE THREAD

**Issue by fisart** [volker76/tuya_mqtt.net#22]
I  am not able to connect to my local Tuya devices. I am able to control them via the Tuya IoT website and via Google assistant  and also with the Smart Life app.

I get the following error message in the logfile when I test the connection

`7/12/2024 12:45:57 PM INFO  MQTT establish reconnection
7/12/2024 12:45:57 PM INFO  MQTT client connected to 192.168.0.112:1912
7/12/2024 7:09:37 PM INFO  Test connection to Tuya API successful.
7/12/2024 8:03:05 PM WARN  Error testing 84.170.234.50
                     System.Exception
                     One or more errors occurred. (Connection timeout)
                        at tuya_mqtt.net.Services.TuyaCommunicatorService.TestConnectLocal0A(TuyaDeviceInformation device) in /src/Services/TuyaCommunicatorService.cs:line 249
   at tuya_mqtt.net.Services.TuyaCommunicatorService.TestConnect(TuyaDeviceInformation device) in /src/Services/TuyaCommunicatorService.cs:line 175
   at tuya_mqtt.net.Pages.TuyaDevices.TestTuyaDevice() in /src/Pages/TuyaDevices.razor:line 408
`
It shouldn't make a difference but for completeness I am using the WesternAmerica  Datacenter since some of my devices are in Florida

BestEx (IP-Symcon)

**Comment by volker76** [comment]
let me have a check - could be TUYA may have chnanged anything in their API.

**Comment by fisart** [comment]
I am happy to support your efforts in any way I can

**Comment by fisart** [comment]
Dont know if this helps but here are the LED`s I have installed and I have problems with
![PXL_20240717_075132516](https://github.com/user-attachments/assets/3ebe32d3-4569-48be-9a9b-d7351287c78e)
![PXL_20240717_075126827 MP](https://github.com/user-attachments/assets/40674b3d-94ff-4c6d-809d-ad6d5c01356e)
