### ISSUE TITLE
Logging page results in Exception 

### ISSUE THREAD

**Issue by volker76** [volker76/tuya_mqtt.net#5]
## when opining the **_System logging_** page, immedeately an exception is raised.

seen in v0.9.5

```
[2023-10-01T17:46:30.378Z] Error: System.AggregateException: One or more errors occurred. (JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.)
 ---> Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at tuya_mqtt.net.Services.BrowserService.GetElementClientRectAsync(ElementReference element) in C:\Users\Volker.SPIELHAUS\source\repos\tuya_mqtt.net\tuya_mqtt.net\Services\BrowserService.cs:line 149
   at tuya_mqtt.net.Pages.Logger.OnAfterRenderAsync(Boolean firstRender) in C:\Users\Volker.SPIELHAUS\source\repos\tuya_mqtt.net\tuya_mqtt.net\Pages\Logger.razor:line 30
   --- End of inner exception stack trace ---
log @ blazor.server.js:1
pr @ blazor.server.js:1
(anonym) @ blazor.server.js:1
_invokeClientMethod @ blazor.server.js:1
_processIncomingData @ blazor.server.js:1
Ft.connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
```

**Comment by volker76** [comment]
adressed in v0.9.7

**Comment by volker76** [comment]
fixed with release v0.9.8
